config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    password: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'homes#top'
  get '/log/hashtag/:name' => 'logs#hashtag'
  get '/log/hashtag' => 'logs#hashtag'

  resources :notifications, only: [:index]
  resources :directs, only: [:index]

  resources :ranks, only: [:index] do
    collection do
      get 'search'
    end
  end

  resources :logs do
    resources :log_comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
    resource :bookmarks, only: %i[create destroy]
  end
  resources :users, only: %i[show edit update] do
    member do
      get :follow, :follower
      get :my_page
      get :dive_profile
      get :unsubscribe
      get :bookmark_list
      patch :withdraw
    end
    resource :relationships, only: %i[create destroy]
  end

  resources :rooms, only: %i[index show create]
  resources :messages, only: [:create]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  attachment :best_point_image

  validates :profile_image, presence: true, on: :update
  validates :nick_name, presence: true, length: { maximum: 30 }, uniqueness: true, on: :update
  validates :name, presence: true, uniqueness: true
  validates :telephone_number, presence: true

  has_many :logs, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :log_comments, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :rooms, through: :entries
  has_many :bookmarks, dependent: :destroy

  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy # 自分からの通知
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy # 相手からの通知

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      # ユーザーを見つける、なければ作成する
      user.name = 'ゲスト'
      user.telephone_number = '00000000000'
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end

  def active_for_authentication?
    super && !is_deleted
  end

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(['visitor_id = ? and visited_id = ? and action = ? ', current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :ensure_normal_user, only: :create

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  def ensure_normal_user
    redirect_to new_user_session_path if params[:user][:email].downcase == 'guest@example.com'
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :ensure_normal_user, only: %i[update destroy]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  def ensure_normal_user
    redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません' if resource.email == 'guest@example.com'
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    WelcomeMailer.with(user: resource).welcome_email.deliver_later
    edit_user_path(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    edit_user_path(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_user, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to logs_path, notice: 'ゲストユーザとしてログインしました'
  end

  def reject_user
    @user = User.find_by(name: params[:user][:name])
    if @user && !@user.active_for_authentication?
      flash[:notice] = '退会済みです。再度ご登録をしてご利用ください。'
      redirect_to new_user_registration_path
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[show edit update dive_profile follow follower]

  def show
    render :my_page if @user.id == current_user.id
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id
            @isRoom = true
            @roomid = cu.room_id
          end
        end
      end
      unless @isRoom
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    if @user == current_user
      render 'edit'
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    if @user.update(user_params)
      redirect_to my_page_user_path(current_user.id)
    else
      render :edit
    end
  end

  def my_page
    @user = User.find(current_user.id)
  end

  def unsubscribe
    @user = User.find(params[:id])
    redirect_to my_page_user_path unless @user == current_user
  end

  def withdraw
    @user = User.find(params[:id])
    if @user.email == 'guest@example.com'
      redirect_to my_page_user_path(@user)
    else
      @user.update(is_deleted: true)
      reset_session
      flash[:alert] = '退会処理を実行いたしました'
      redirect_to root_path
    end
  end

  def dive_profile
    @log = @user.logs
  end

  def follow
    @follow = @user.following_user
  end

  def follower
    @follower = @user.follower_user
  end

  def bookmark_list
    @bookmarks = Bookmark.includes(:log).where(user_id: current_user.id)
  end

  private

  def user_params
    params.require(:user).permit(:profile_image, :nick_name, :introduction, :license_rank, :best_point,
                                 :best_point_image)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit.html.erb
<%= form_with model: user, local: true do |f| %>
  <div class="form">
    <%= f.label :プロフィール画像 %><br />
    <%= f.attachment_field :profile_image, class: "#{"is-invalid" if user.errors.include?(:profile_image)}" %>
  </div>

  <div class="form">
    <%= f.label :ニックネーム %><br />
    <%= f.text_field :nick_name, class: "form-control #{"is-invalid" if user.errors.include?(:nick_name)}" %>
  </div>

  <div class="form">
    <%= f.label :自己紹介 %><br />
    <%= f.text_field :introduction, class: "form-control" %>
  </div>

  <div class="form">
    <%= f.label :ダイビングライセンス %><br />
    <%= f.text_field :license_rank, class: "form-control" %>
  </div>

  <div class="form">
    <%= f.label :一番の思い出ポイント %><br />
    <%= f.text_field :best_point, class: "form-control" %>
  </div>

  <div class="form">
    <%= f.label :思い出画像 %><br />
    <%= f.attachment_field :best_point_image %>
  </div>

  <div class="row edit-btn">
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 offset-xs-3 offset-sm-3 offset-md-3 offset-lg-3">
      <%= f.submit '編集', class: "btn edit-btn-gradation rounded-pill" %>
    </div>
  </div>

<% end %>

app/views/users/_show.html.erb
<% unless user.logs.empty? %>
  <div class="row mt-5 border border-light shadow-lg">
    <% user.logs.reverse.each do |user_log| %>
      <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 mt-5 mb-5 text-center user-memory">
        <%= user_log.created_at.strftime('%Y/%m/%d') %><br />
        <%= link_to log_path(user_log.id) do %><%= attachment_image_tag user_log, :log_image, size: "210x210", class: "w-100" %><% end %>
      </div>
    <% end %>
  </div>
<% else %>
  <div></div>
<% end %>

app/views/users/_user-image.html.erb
<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 text-center mx-auto pt-5">
  <%= attachment_image_tag user, :profile_image, size: "300x300", class: "rounded-circle" %><br />
</div>

<div class="col-xs-5 col-sm-5 col-md-5 col-lg-5 mt-4 text-dark">
  <div class="name mb-3">
    <% if user.nick_name %>
      <span class="h3"><%= user.nick_name %></span>
      <small>by  <%= user.name %></small><br />
    <% else %>
      <%= user.name %>
    <% end %>
  </div>

  <div class="name mb-3">
    <%= user.introduction %>
  </div>

  <div class="log_count">
    <p>投稿数　<%= user.logs.count %></p>
  </div>

app/views/users/bookmark_list.html.erb
<div class="container all">
  <h1 class="logo text-center mb-5">My Bookmark List</h1>

  <div clas="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <% if @bookmarks.present? %>
        <div class="row border border-light shadow-lg">
          <% @bookmarks.reverse.each do |mark|%>
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 mt-5 mb-5 text-center user-memory">
              <%= link_to log_path(mark.log) do %><%= attachment_image_tag mark.log, :log_image, size: "210x210", class: "w-100" %><% end %>
            </div>
          <% end %>
        </div>
      <% else %>
        <div></div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/dive_profile.html.erb
<div class="container all">
  <h1 class="logo text-center mb-5"><%= @user.nick_name %> Dive Profile</h1>
  <div class="row">
    <div class="col"></div>
    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
      <table class="table table-bordered table-hover">
        <tbody class="text-center">
          <tr class="bg-light">
            <th>ライセンスランク</th>
          </tr>
          <tr><td><%= @user.license_rank %></td></tr>
          <tr class="bg-light"><th>累計潜水本数</th></tr>
          <tr>
            <td>
              <% @sum = 0 %>
              <% @log.each do |log|%>
                <% @sum += log.dive_number.to_i %>
              <% end %>
              <%= @sum %> 本
            </td>
          </tr>
          <tr class="bg-light"><th>最高潜水深度</th></tr>
          <tr>
            <td><%= @log.maximum(:dive_depth) %> M</td>
          </tr>
          <tr class="bg-light">
            <th>一番の思い出ポイント</th>
          </tr>
          <tr>
            <td><%= @user.best_point %></td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
      <%= attachment_image_tag @user, :best_point_image, size: "400x400" %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container all text-dark">
  <div class="row">
    <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10 offset-xs-1 offset-sm-1 offset-md-1 offset-lg-1 border border-light shadow-lg bg-light pt-4 pb-4">
      <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 offset-xs-3 offset-sm-3 offset-md-3 offset-lg-3">
          <h1 class="logo text-center mb-5">Edit Profile</h1>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 offset-xs-3 offset-sm-3 offset-md-3 offset-lg-3 text-center text-danger mb-5">
          <% if @user.errors.any? %>
            <div id="error_explanation">
              <strong><%= @user.errors.count %>件のエラーが発生しました</strong><br />
              <h5 class="text-danger">入力内容を確認してください</h5>
              <% @user.errors.full_messages.each do |message| %>
                <%= message %><br />
              <% end %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 offset-xs-3 offset-sm-3 offset-md-3 offset-lg-3">
          <%= render "users/edit", user: @user %>

          <div class="row danger-btn">
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 offset-xs-3 offset-sm-3 offset-md-3 offset-lg-3">
              <%= link_to unsubscribe_user_path, class: "btn danger-btn-gradation rounded-pill" do %>退会画面へ<% end %>
            <div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/follow.html.erb
<div class="container all">
  <div class="row mt-5">
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 offset-xs-3 offset-sm-3 offset-md-3 offset-lg-3">

      <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 offset-xs-3 offset-sm-3 offset-md-3 offset-lg-3 text-center">
          <h2 class="logo mb-3">follow</h2>
        </div>
      </div>
      
      <% if @follow.present? %>
        <div class="row bg-light">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center">
            <table class="table table-border-bottom">
              <tbody>
                <% @follow.each do |follow| %>
                <tr>
                  <td><%= link_to user_path(follow.id), class: "text-dark" do %><%= attachment_image_tag follow, :profile_image, size: "50x50", class: "rounded-circle" %><% end %></td>
                  <td>
                    <%= link_to user_path(follow.id), class: "text-dark" do %>
                      <% if follow.nick_name %>
                        <span><strong><%= follow.nick_name %></strong><small> by  <%= follow.name %></small></span>
                      <% else %>
                        <%= follow.name %>
                      <% end %>
                    <% end %>
                  </td>
                  <td>
                    <% if current_user != follow %>
                      <span class="ml-2" id="follow_<%= follow.id %>">
                        <%= render 'relationships/follow', user: follow %>
                      </span>
                    <% end %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/users/follower.html.erb
<div class="container all">
  <div class="row mt-5">
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 offset-xs-3 offset-sm-3 offset-md-3 offset-lg-3">

      <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 offset-xs-3 offset-sm-3 offset-md-3 offset-lg-3 text-center">
          <h2 class="logo mb-3">follower</h2>
        </div>
      </div>

      <% if @follower.present? %>
        <div class="row bg-light">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center">
            <table class="table table-border-bottom">
              <tbody>
                <% @follower.each do |follower| %>
                <tr>
                  <td><%= link_to user_path(follower.id), class: "text-dark" do %><%= attachment_image_tag follower, :profile_image, size: "50x50", class: "rounded-circle" %><% end %></td>
                  <td>
                    <%= link_to user_path(follower.id), class: "text-dark" do %>
                      <% if follower.nick_name %>
                        <span><strong><%= follower.nick_name %></strong><small> by  <%= follower.name %></small></span>
                      <% else %>
                        <%= follower.name %>
                      <% end %>
                    <% end %>
                  </td>
                  <td>
                    <% if current_user != follower %>
                      <span class="ml-2" id="follow_<%= follower.id %>">
                        <%= render 'relationships/follow', user: follower %>
                      </span>
                    <% end %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/users/my_page.html.erb
<div class="container all">
  <div class="row mt-5">
    <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10 mx-auto">

      <div class="row">

        <%= render "users/user-image", user: @user %>

          <div class="follow-follower mb-3">
            <span class="follow">
              <%= link_to follow_user_path(@user), class: "text-dark" do %><%= current_user.follower.count %>フォロー<% end %>
            </span>

            <span class="follower">
              <%= link_to follower_user_path(@user), class: "text-dark" do %><%= current_user.followed.count %>フォロワー<% end %><br />
            </span>
          </div>

          <div class="profile mb-3">
            <p><%= link_to dive_profile_user_path(@user.id), class: "btn btn-outline-secondary" do %><i class="far fa-file-alt"></i> Diving Profile<% end %></p>
            <% if @user == current_user %>
              <p><%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary" do %><i class="fas fa-user-cog"></i> Edit Profile<% end %></p>
              <p><%= link_to bookmark_list_user_path(@user.id), class: "btn btn-outline-secondary" do %><i class="fas fa-bookmark"></i> Bookmark List<% end %></p>
            <% end %>
          </div>
        </div>
      </div>
      <h1 class="logo text-center mt-5">My Memories</h1>
      <%= render 'show', user: @user %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container all">
  <div class="row mt-5">
    <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10 mx-auto">

      <div class="row">

        <%= render "users/user-image", user: @user %>

          <div class="follow-follower mb-3">
            <span class="follow_count_<%= @user.id %> mr-2">
              <%= link_to follow_user_path(@user), class: "text-dark" do %><%= @user.follower.count %>フォロー<% end %>
            </span>

            <span class="follower_count_<%= @user.id %>">
              <%= link_to follower_user_path(@user), class: "text-dark" do %><%= @user.followed.count %>フォロワー<% end %><br />
            </span>
          </div>

          <div class="follow-btn">
            <% if current_user != @user %>
              <span id="follow_<%= @user.id %>">
                <%= render 'relationships/follow', user: @user %>
              </span>
            <% end %>
          </div>

          <div class="profile mt-3 mb-3">
            <%= link_to dive_profile_user_path(@user.id), class: "btn btn-outline-secondary" do %><i class="far fa-file-alt"></i> Diving Profile<% end %>
          </div>

          <div class="message">
            <% if @user != current_user %>
              <% if @isRoom == true %>
                <%= link_to room_path(@roomid), class: "btn btn-outline-secondary" do %><i class="fas fa-envelope"></i> メッセージを送信<% end %>
              <% else %>
                <%= form_with model: @room, url: rooms_path, method: :post, local: true do |f| %>
                  <%= fields_for @entry do |e| %>
                    <%= e.hidden_field :user_id, value: @user.id%>
                  <% end %>
                  <%= f.submit 'メッセージを始める', class: "btn btn-outline-secondary" do %><i class="fas fa-envelope"></i><% end %>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <h1 class="logo text-center mt-5"><%= @user.nick_name %> Memories</h1>
      <%= render 'show', user: @user %>
    </div>
  </div>
</div>

app/views/users/unsubscribe.html.erb
<div class="container all">
  <div class="row">
    <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10 offset-xs-1 offset-sm-1 offset-md-1 offset-lg-1">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

          <h1 class="text-center mb-5"><%= @user.name %>さん</h1>

          <table class="table table-borderless">
            <thead>
              <th class="h1 text-center"><strong><i class="fas fa-exclamation-triangle text-warning"></i>退会確認<i class="fas fa-exclamation-triangle text-warning"></i></strong></th>
            </thead>
            <tbody>
              <tr>
                <td class="text-center">
                  一度退会すると今後このアカウントは使用できなくなります<br />
                  本当に退会してもよろしいですか？
                </td>
              </tr>
              <tr>
                <td></td>
              </tr>
              <tr></tr>
            </tbody>
          </table>

        </div>
      </div>

      <div class="row">
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 offset-xs-1 offset-sm-1 offset-md-1 offset-lg-1 edit-btn">
          <%= link_to my_page_user_path(current_user.id), class: "btn edit-btn-gradation rounded-pill" do %>退会しない<% end %>
        </div>

        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 offset-xs-2 offset-sm-2 offset-md-2 offset-lg-2 danger-btn">
          <%= link_to withdraw_user_path, method: :patch, data: { confilm: "本当に退会しますか？" }, class: "btn danger-btn-gradation rounded-pill" do %>退会する<% end %>
        </div>
      </div>

    </div>
  </div>
</div>