config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    password: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'homes#top'
  get '/log/hashtag/:name' => 'logs#hashtag'
  get '/log/hashtag' => 'logs#hashtag'

  resources :notifications, only: [:index]
  resources :directs, only: [:index]

  resources :ranks, only: [:index] do
    collection do
      get 'search'
    end
  end

  resources :logs do
    resources :log_comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
    resource :bookmarks, only: %i[create destroy]
  end
  resources :users, only: %i[show edit update] do
    member do
      get :follow, :follower
      get :my_page
      get :dive_profile
      get :unsubscribe
      get :bookmark_list
      patch :withdraw
    end
    resource :relationships, only: %i[create destroy]
  end

  resources :rooms, only: %i[index show create]
  resources :messages, only: [:create]
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :users, through: :entries
  has_many :notifications, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def create
    @room = Room.create
    Entry.create(room_id: @room.id, user_id: current_user.id)
    Entry.create(rooms_params.merge(room_id: @room.id))
    redirect_to room_path(@room.id)
  end

  def index
    @user = current_user
    @currentEntries = current_user.entries.includes(:room)
    myRoomIds = []
    @currentEntries.each do |entry|
      myRoomIds << entry.room.id
    end
    @anotherEntries = Entry.includes(:user).where(room_id: myRoomIds).where('user_id != ?', @user)
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entry = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
  
  private
  
  def rooms_params
    params.require(:entry).permit(:user_id, :room_id)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<div class="container all">
  <div class="row">
    <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
      <div class="row mb-5">
        <div class="col-sm-8 offset-sm-2">
          <span class="dm_host_user"><%= link_to logs_path, class: "text-dark" do %><i class="fas fa-chevron-left"></i><% end %>　  <strong><%= current_user.nick_name %></strong></th>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10 offset-xs-1 offset-sm-1 offset-md-1 offset-lg-1">
          <table class="table table-border-bottom dm_list">
            <tbody>
              <% @anotherEntries.includes(:room).each do |e, index| %>
                <tr>
                  <td>
                    <%= link_to user_path(e.user_id), class: "text-dark" do %>
                      <%= attachment_image_tag e.user, :profile_image, size: "50x50", class: "rounded-circle" %>
                      <span class="dm_user ml-2"><strong><%= e.user.name %></strong></span>
                    <% end %>
                  </td>
                  <td class="edit-btn"><%= link_to room_path(e.room), class: 'btn edit-btn-gradation ml-4' do %><span class="dm_user_room">メッセージを送る</span><% end %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="container all">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

      <div class="row mb-5">
        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8 offset-xs-2 offset-sm-2 offset-md-2 offset-lg-2">
          <div class="new_message">
            <%= link_to rooms_path, class: "btn back-btn" do %><strong><i class="fas fa-chevron-left"></i></strong><% end %>
            <% @entry.includes(:user).each do |e| %>
              <% unless e.user == current_user %>
                <%= attachment_image_tag e.user, :profile_image, size: "70x70", class: "rounded-circle" %>
                <strong><span class="message_my_name"><%= e.user.name %></span></strong>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8 offset-xs-2 offset-sm-2 offset-md-2 offset-lg-2">
          <div class="message">
            <% @messages.each do |message| %>
              <% if message.user_id == current_user.id %>
                <div class="mycomment mt-1 mb-1">
                  <p class="my-dm ml-auto"><%= message.content %></p>
                </div>
              <% else %>
                <p class="other-dm"><%= message.content %></p>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>

      <div class="row mt-3">
        <div class="col"></div>
        <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7 offset-xs-1 offset-sm-1 offset-md-1 offset-lg-1">
          <div class="new_message">
            <%= form_with model: @message, url: messages_path, method: :post do |f| %>
              <%= f.text_field :content, size: 60, id: "new_message" %>
              <%= f.hidden_field :room_id, value: @room.id %>
              <%= f.submit '送信', class: 'btn message-btn text-dark' %>
            <% end %>
          </div>
        </div>
        <div class="col"></div>
      </div>
    </div>
  </div>
</div>