config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    password: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'homes#top'
  get '/log/hashtag/:name' => 'logs#hashtag'
  get '/log/hashtag' => 'logs#hashtag'

  resources :notifications, only: [:index]
  resources :directs, only: [:index]

  resources :ranks, only: [:index] do
    collection do
      get 'search'
    end
  end

  resources :logs do
    resources :log_comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
    resource :bookmarks, only: %i[create destroy]
  end
  resources :users, only: %i[show edit update] do
    member do
      get :follow, :follower
      get :my_page
      get :dive_profile
      get :unsubscribe
      get :bookmark_list
      patch :withdraw
    end
    resource :relationships, only: %i[create destroy]
  end

  resources :rooms, only: %i[index show create]
  resources :messages, only: [:create]
end

app/models/log.rb
class Log < ApplicationRecord
  attachment :log_image

  validates :log_image, presence: true
  validates :weather, presence: true
  validates :dive_depth, presence: true
  validates :dive_number, presence: true
  validates :dive_point, presence: true
  validates :water_temperature, presence: true
  validates :title, length: { maximum: 20 }
  validates :body, length: { maximum: 150 }
  validates :address, presence: true

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :log_comments, dependent: :destroy
  # has_many :replies, class_name: "LogComment", foreign_key: :reply_comment, dependent: :destroy
  has_many :hashtag_logs, dependent: :destroy
  has_many :hashtags, through: :hashtag_logs
  has_many :bookmarks, dependent: :destroy
  has_many :notifications, dependent: :destroy

  geocoded_by :address
  after_validation :geocode

  enum weather: {
    ☀️: 0,
    🌥: 1,
    ☔: 2
  }

  is_impressionable counter_cache: true, unique: true

  def favorited_by?(user)
    favorites.where(user_id: user).exists?
  end

  def bookmarked_by?(user)
    bookmarks.where(user_id: user).exists?
  end

  # DBへのコミット直前に実施する
  after_create do
    log = Log.find_by(id: id)
    # 正規表現でLogのhashbodyの「#」がついた文字列を検索する
    hashtags = hashbody.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    # hashtags変数の中で、重複するものは除外し、配列として返す（それをブロック変数で使えるようにする）
    hashtags.uniq.map do |hashtag|
      # ハッシュタグは先頭の'#'を外した上で保存　find_or_create_byメソッドで、データにない場合は作る
      tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#'))
      # logのhashtagsに上記の情報を入れる
      log.hashtags << tag
    end
  end

  # 更新時のメソッド
  before_update do
    log = Log.find_by(id: id)
    log.hashtags.clear
    hashtags = hashbody.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#'))
      log.hashtags << tag
    end
  end

  def create_notification_favorite!(current_user)
    # すでにいいねされているか検索
    temp = Notification.where(['visitor_id = ? and visited_id = ? and log_id = ? and action = ? ', current_user.id,
                               user_id, id, 'favorite'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        log_id: id,
        visited_id: user_id,
        action: 'favorite'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      notification.checked = true if notification.visitor_id == notification.visited_id
      notification.save # （エラーが発生した場合はture, ない場合はfalseを返す）
    end
  end

  def create_notification_comment!(current_user, log_comment_id)
    # 自分以外にコメントしている人を全て取得し、全員に通知を送る
    temp_ids = LogComment.select(:user_id).where(log_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, log_comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, log_comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, log_comment_id, visited_id)
    # コメントが複数回することが考えられるため、一つの投稿医複数回通知する
    notification = current_user.active_notifications.new(
      log_id: id,
      log_comment_id: log_comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    notification.checked = true if notification.visitor_id == notification.visited_id
    notification.save if notification.valid?
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_log, only: %i[edit update destroy]

  def new
    @log = Log.new
  end

  def create
    @log = Log.new(log_params)
    @log.user_id = current_user.id
    if @log.save
      redirect_to logs_path, notice: 'You have created log successfully.'
    else
      render :new
    end
  end

  def index
    @logs = Log.all.includes(:user)
  end

  def show
    @log = Log.includes(log_comments: %i[user replies]).find(params[:id])
    @logcomment = LogComment.new
    gon.log = @log
    impressionist(@log, nil, unique: [:session_hash.to_s])
  end

  def edit
    if @log.user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    if @log.update(log_params)
      redirect_to log_path(@log)
    else
      render :edit
    end
  end

  def destroy
    @log.destroy
    redirect_to logs_path
  end

  def hashtag
    @user = current_user
    if params[:name].nil?
      @hashtags = Hashtag.all.to_a.group_by { |hashtag| hashtag.logs.count }
    else
      @hashtag = Hashtag.find_by(hashname: params[:name])
      @log = @hashtag.logs.page(params[:page]).per(20).reverse_order
      @hashtags = Hashtag.all.to_a.group_by { |hashtag| hashtag.logs.count }
    end
  end

  private

  def set_log
    @log = Log.find(params[:id])
  end

  def log_params
    params.require(:log).permit(:log_image, :title, :body, :weather, :water_temperature, :dive_number, :dive_depth,
                                :dive_point, :hashbody, :address, :latitude, :longitude)
  end
end

app/helpers/logs_helper.rb
module LogsHelper
  def render_with_hashtags(hashbody)
    # gsubで(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)を検索した後、{}の部分で、持ってきた情報にリンクを付加させエスケープ処理せずに置換する
    # ※DELETEメソッドがあるが、表示される時ではなく、リンク先のルーティングを指定する際に＃が邪魔になるから削除している
    hashbody.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/) do |word|
      link_to word, "/log/hashtag/#{word.delete('#')}", data: { 'turbolinks' => false }
    end.html_safe
  end
end

app/views/logs/_bookmark.html.erb
<% if log.bookmarked_by?(current_user) %>
  <%= link_to log_bookmarks_path(log), method: :delete, remote: true, class: "text-dark" do %><i class="fas fa-bookmark"></i><% end %>
<% else %>
  <%= link_to log_bookmarks_path(log), method: :post, remote: true, class: "text-dark" do %><i class="far fa-bookmark"></i><% end %>
<% end %>

app/views/logs/_comment.html.erb
<% log.log_comments.each do |comment| %>
  <% if comment.reply_comment.present? %>
    <% next %>
  <% end %>
  <!--reply_commentが存在しているコメントはスルーしてください＝返信コメントはスルーして大元のコメントだけ繰り返してください-->
    <span id="comment_<%= comment.id %>">
      <%= link_to user_path(comment.user.id), class: "text-dark" do %>
        <%= attachment_image_tag comment.user, :profile_image, size: "50x50", class: "rounded-circle" %>
        <strong><%= comment.user.name %></strong>
      <% end %>
      <%= comment.comment %>

      <div class="row mt-1">
        <div class="col-sm-8">
          <%= form_with(model:[log, LogComment.new]) do |f| %>
            <%= f.text_field :comment, class: "rounded-pill form-control" %>
            <%= f.hidden_field :reply_comment, :value => comment.id  %>
            <%= f.submit "返信する", class: "btn" %>
          <% end %>
        </div>
      </div>

      <!--ここの部分が返信コメントの記述。２０pxにしてるから小さくなる-->
      <% if comment.replies.present? %>
        <% comment.replies.each do |reply| %>
          <p style="padding-left: 20px;">
            <%= attachment_image_tag reply.user, :profile_image, size: "25x25", class: "rounded-circle" %>
            <%= reply.user.name %>
            <%= reply.comment %>
          </p>
        <% end %>
      <% end %>
    </span><br />
<% end %>

app/views/logs/_favo.html.erb
<% if log.favorited_by?(current_user) %>
  <%= link_to log_favorites_path(log.id), method: :delete, remote: true, class: "text-danger" do %>❤<% end %><%= log.favorites.count %><br />
<% else %>
  <%= link_to log_favorites_path(log.id), method: :post, remote: true, class: "text-dark" do %>♡<% end %><%= log.favorites.count %><br />
<% end %>

app/views/logs/_log-error.html.erb
<% if log.errors.any? %>
  <div id="error_explanation">
    <strong><%= log.errors.count %>件のエラーが発生しました</strong><br />
    <h5 class="text-danger">入力内容を確認してください</h5>
    <ul class="h6" style="list-style: none;">
    <% log.errors.full_messages.each do |message| %>
      <%= message %><br />
    <% end %>
    </ul>
  </div>
<% end %>

app/views/logs/_log-form.html.erb
<%= form_with model: log, local: true do |f| %>
  <div class="row text-dark">
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
      <div class="row">
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 mx-auto">
          <div class="form mb-3">
            <%= f.label :画像 %><br />
            <%= f.attachment_field :log_image, class: "#{"is-invalid" if log.errors.include?(:log_image)}" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 mx-auto">
          <div class="form mb-3">
            <%= f.label :天気 %><br />
            <%= f.select :weather, options_for_select(Log.weathers.keys), class: "form-control #{"is-invalid" if log.errors.include?(:weather)}" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 mx-auto">
          <div class="form mb-3">
            <%= f.label :水温 %>
            <%= f.select :water_temperature, options_for_select((0..30).to_a), {prompt: '選択'}, class: "form-control #{"is-invalid" if log.errors.include?(:water_temperature)}" %>℃
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 mx-auto">
          <div class="form mb-3">
            <%= f.label :潜水深度 %>
            <%= f.select :dive_depth, options_for_select((0..50).to_a), {prompt: '選択'}, class: "form-control #{"is-invalid" if log.errors.include?(:dive_depth)}" %>M
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 mx-auto">
          <div class="form mb-3">
            <%= f.label :潜水本数 %>
            <%= f.select :dive_number, options_for_select((0..5).to_a), {prompt: '選択'}, class: "form-control #{"is-invalid" if log.errors.include?(:dive_number)}" %>本
          </div>
        </div>
      </div>

    </div>

    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
      <div class="row">
        <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
          <div class="form mb-3">
            <%= f.label :ダイビングポイント %>
            <%= f.text_field :dive_point, placeholder: "沖縄県---", class: "form-control #{"is-invalid" if log.errors.include?(:dive_point)}" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
          <div class="form mb-3">
            <%= f.label :タイトル %>
            <%= f.text_field :title, placeholder: "20文字まで", class: "form-control #{"is-invalid" if log.errors.include?(:title)}" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
          <div class="form mb-3">
            <%= f.label :内容 %>
            <%= f.text_area :body, class: "form-control #{"is-invalid" if log.errors.include?(:body)}", rows: "6", placeholder: "150文字まで" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
          <div class="form mb-3">
            <%= f.label :タグ %>
            <%= f.text_field :hashbody, placeholder: "#diving #diver", class: "form-control" %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row pt-5">
    <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10 text-center mx-auto map">
      <%= f.label :デモ検索 %>
      <input id="address" type="textbox" value="Sydney, NSW">
      <input type="button" value="検索" onclick="codeAddress()">
      <div class="row">
        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8 mx-auto">
          <%= f.text_field :address, class: "form-control #{"is-invalid" if log.errors.include?(:address)} mt-3 mb-4", placeholder: "住所をここに" %>
        </div>
      </div>
      <div id='map' style="width: 100%; height: 500px;"></div>
    </div>
  </div>

  <div class="row custom-btn">
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 offset-xs-3 offset-sm-3 offset-md-3 offset-lg-3">
      <%= f.submit '投稿', class: "btn btn-gradation rounded-pill" %>
    </div>
  </div>

<% end %>

app/views/logs/_log.html.erb
<div class="col-xs-7 col-sm-7 col-md-7 col-lg-7 pt-5">
  <div class="row logo-text">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <h1 class="logo text-center">Memories</h1>
    </div>
  </div>
  <% logs.reverse.each do |log| %>
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 logs text-dark shadow-lg bg-white mb-5 pt-3 pb-3">

      <div class="row">
        <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10 index-user float-left">
          <% if log.user != current_user %>
            <%= link_to user_path(log.user_id) do %>
              <p class="text-dark">
                <%= attachment_image_tag log.user, :profile_image, size: "50x50", class: "rounded-circle" %>
                <%= log.user.name %>
              </p>
            <% end %>
          <% else %>
            <%= link_to my_page_user_path(current_user.id) do %>
              <p class="text-dark">
                <%= attachment_image_tag current_user, :profile_image, size: "50x50", class: "rounded-circle" %>
                <%= current_user.name %>
              </p>
            <% end %>
          <% end %>

          <h5><strong><%= log.title %></strong></h5>
          <%= log.dive_point %>
        </div>

        <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2 log-edit align-items-end">
          <% if log.user == current_user %>
            <%= link_to edit_log_path(log.id), class: "float-right text-dark" do %><i class="fas fa-cog"></i><% end %><br />
          <% end %>
        </div>
      </div>

      <div class="row log-image text-center">
        <%= link_to log_path(log.id) do %><%= attachment_image_tag log, :log_image, size: "1000x1000", class: "img-fluid w-100 h-auto" %><% end %><br />
      </div>

      <div class="row">
        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
          <span id="log_bookmark_<%= log.id %>">
            <%= render 'logs/bookmark', log: log %>
          </span>
        </div>
        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
          <span id="log_<%= log.id %>">
            <%= render 'logs/favo', log: log %>
          </span>
        </div>

        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 text-center">
          <i class="far fa-comments"></i><%= log.log_comments.count %>
        </div>

        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 mx-auto text-right">
          <strong><%= log.impressionist_count %>PV</strong><br />
        </div>

      </div>

    </div>
  </div>
  <% end %>
</div>

app/views/logs/_logs.html.erb
<%= render_with_hashtags(log.body) %>

app/views/logs/hashtag.html.erb
<div class="container all">
  <div class="row">
    </div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">

    <div class="row mb-5">
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 offset-xs-3 offset-sm-3 offset-md-3 offset-lg-3 text-center">
        <h2 class="logo">Hashtag</h2>
      </div>
    </div>

    <% unless params[:name] == nil %>
      <div class="row mb-5">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <% @log.each do |log| %>
            <%= link_to log_path(log.id) do %><%= attachment_image_tag log, :log_image, size: "200x200", class: "mb-1" %><% end %>
          <% end %>
        </div>
      </div>

      <div class="row border-top dorder-dark pt-2">
        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8 offset-xs-2 offset-sm-2 offset-md-2 offset-lg-2 hashtag-name">
          <% @hashtags.sort.reverse.each do |count| %>
            <% count[1].each do |hashtag| %>
              <%= link_to  "##{hashtag.hashname} (#{hashtag.logs.count}) 件","/log/hashtag/#{hashtag.hashname}",data: {"turbolinks" => false} %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>

    </div>
  </div>
</div>

app/views/logs/index.html.erb
<div class="container all">

  <div class="row mt-5">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 mx-auto">

      <div class="row">

        <% if user_signed_in? %>
          <% unless current_user.logs.empty? %>
            <%= render 'logs/log', logs: @logs %>
          <% else %>
            <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7 pt-3"><br /><br />
            <div class="row">
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <h1 class="logo text-center logo-text">Memories</h1>
              </div>
            </div>
            <h2 class="text-center">さぁ、思い出を投稿しよう！</h2><br /><br />
            <p class="text-center">初投稿はここからできるよ！</p>
            <p class="custom-btn"><%= link_to new_log_path, class: "btn-gradation rounded-pill" do %>投稿する<% end %></p><br />
              <% @logs.reverse.each do |log| %>
            <div class="row">
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 logs text-dark shadow-lg bg-white border border-light mb-5 pt-3 pb-3 content">
                <div class="row">
                  <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10 index-user float-left">
                    <% if log.user != current_user %>
                      <%= link_to user_path(log.user_id) ,class: "text-dark" do %>
                        <p class="text-dark">
                          <%= attachment_image_tag log.user, :profile_image, size: "50x50", class: "rounded-circle" %>
                          <%= log.user.name %>
                        </p>
                      <% end %>
                    <% else %>
                      <%= link_to my_page_user_path(current_user.id) do %>
                        <p class="text-dark">
                          <%= attachment_image_tag current_user, :profile_image, size: "50x50", class: "rounded-circle" %>
                          <%= current_user.name %>
                        </p>
                      <% end %>
                    <% end %>
                    <h5><strong><%= log.title %></strong></h5>
                    <%= log.dive_point %>
                  </div>
                  <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2 log-edit align-items-end">
                    <% if log.user == current_user %>
                      <%= link_to edit_log_path(log.id), class: "float-right pt-4 text-dark" do %><i class="fas fa-cog"></i><% end %><br />
                    <% end %>
                  </div>
                </div>
                <div class="row log-image text-center">
                  <%= link_to log_path(log.id) do %><%= attachment_image_tag log, :log_image, size: "1000x1000", class: "img-fluid w-100 h-auto" %><% end %><br />
                </div>
                <div class="row">
                  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                    <span id="log_bookmark_<%= log.id %>">
                      <%= render 'logs/bookmark', log: log %>
                    </span>
                  </div>
                  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                    <span id="log_<%= log.id %>">
                      <%= render 'logs/favo', log: log %>
                    </span>
                  </div>
                  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 text-center">
                    <i class="far fa-comments"></i><%= log.log_comments.count %>
                  </div>
                  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 mx-auto text-right">
                    <strong><%= log.impressionist_count %>PV</strong><br />
                  </div>
                </div>
              </div>
            </div>
            <% end %>
            </div>
          <% end %>

        <% else %>
          <%= render 'logs/log', logs: @logs %>
        <% end %>
        <% if user_signed_in? %>
          <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 pt-5 shadow-lg bg-white border border-light text" style="height: 430px; position: fixed; right: 150px; top: 130px;">
            <h3 class="text-center logo mb-3">My Profile</h3>

            <table class="table table-borderless">
              <thead>
                <tr><th><%= attachment_image_tag current_user, :profile_image, size: "50x50", class: "rounded-circle" %>　<%= current_user.nick_name %></th></tr>
                <tr><th>ライセンス</th><th><%= current_user.license_rank %></th></tr>
                <tr><th>follow</th><th><%= current_user.following_user.count %></th></tr>
                <tr><th>follower</th><th><%= current_user.follower_user.count %></th></tr>
                <tr><th>投稿数</th><th><%= current_user.logs.count %></th></tr>
              </thead>
            </table>
          </div>
        <% else %>
          <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 text pt-5" style="height: 150px; position: fixed; right: 150px; top: 130px;">
            <h3 class="text-center mb-3">Beginner</h3>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/logs/show.html.erb
<div class="container all">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

      <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 offset-xs-3 offset-sm-3 offset-md-3 offset-lg-3 text-center mb-4">
          <h1 class="logo"><%= @log.user.nick_name %> Memory</h1>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
          <h4><strong><%= @log.title %></strong></h4>
          <p><%= @log.dive_point %></p>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
          <span><%= @log.weather %></span> / <span><%= (@log.water_temperature).to_i %> ℃（水温）</span> / <span><%= (@log.dive_depth).to_i %> M</span> / <span><%= (@log.dive_number).to_i %> 本</span>
          <% if @log.user == current_user %>
            <%= link_to edit_log_path(@log.id), class: "float-right text-dark" do %><i class="fas fa-cog"></i><% end %>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
          <%= attachment_image_tag @log, :log_image, class: "w-100 h-auto" %>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
          <p>
            <% if @log.user != current_user %>
            <%= link_to user_path(@log.user_id) do %>
              <p>
                <%= attachment_image_tag @log.user, :profile_image, size: "50x50", class: "rounded-circle" %>
                <span class="text-dark"><%= @log.user.name %></span>
              </p>
            <% end %>
          <% else %>
            <%= link_to my_page_user_path(current_user.id) do %>
              <p>
                <%= attachment_image_tag current_user, :profile_image, size: "50x50", class: "rounded-circle" %>
                <span class="text-dark"><%= current_user.name %></span>
              </p>
            <% end %>
          <% end %>
          </p>
          <p><%= @log.body %><p>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class="row">
            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
              <span id="log_<%= @log.id %>">
                <%= render 'logs/favo', log: @log %>
              </span>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            <%= render_with_hashtags(@log.hashbody) %>
            </div>
          </div>
        </div>
      </div>

      <div class="row mt-5">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <h2>エリア</h2>
          <h5><%= @log.address %></h5>
          <div id="map" style="width: 100%; height: 500px;"></div>
        </div>
      </div>

      <div class="row mt-5">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 offset-xs-3 offset-sm-3 offset-md-3 offset-lg-3 mx-auto">
          <div id="comment">
            <%= render 'logs/comment', log: @log %>
          </div>
        </div>
      </div>

      <div class="row new_comment">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 offset-xs-3 offset-sm-3 offset-md-3 offset-lg-3">
          <%= form_with(model:[@log, @logcomment], url: log_log_comments_path(@log, @logcomment)) do |f| %>
            <%= f.text_area :comment, placeholder: "#{@log.user.nick_name}のコメント" , class: "form-control rounded-pill", id: "new_comment" %><br />
            <div class="row custom-btn">
              <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 offset-sm-3 offset-xs-3 offset-sm-3 offset-md-3 offset-lg-3">
              <%= f.submit '送信', class: "btn btn-gradation rounded-pill" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

<!--GoogleMapの記述-->
<script>

  let map;

  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      // コントローラーで定義した変数から緯度経度を呼び出し、マップの中心に表示
      center: {
        lat: gon.log.latitude,
        lng: gon.log.longitude
      },
      zoom: 16,
    });

    marker = new google.maps.Marker({
      // コントローラーで定義した変数から緯度経度を呼び出し、マーカーを立てる
      position: {
        lat: gon.log.latitude,
        lng: gon.log.longitude
      },
      map: map
    });
  }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['MY_GOOGLE_MAP_API'] %>&callback=initMap">
</script>