config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    password: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'homes#top'
  get '/log/hashtag/:name' => 'logs#hashtag'
  get '/log/hashtag' => 'logs#hashtag'

  resources :notifications, only: [:index]
  resources :directs, only: [:index]

  resources :ranks, only: [:index] do
    collection do
      get 'search'
    end
  end

  resources :logs do
    resources :log_comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
    resource :bookmarks, only: %i[create destroy]
  end
  resources :users, only: %i[show edit update] do
    member do
      get :follow, :follower
      get :my_page
      get :dive_profile
      get :unsubscribe
      get :bookmark_list
      patch :withdraw
    end
    resource :relationships, only: %i[create destroy]
  end

  resources :rooms, only: %i[index show create]
  resources :messages, only: [:create]
end

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <li class="nav-item">
    <%= link_to logs_path,  class: "nav-link deco text-dark" do %><i class="fas fa-list"></i><% end %>
  </li>

  <li class="nav-item">
    <%= link_to new_log_path, class: "nav-link deco text-dark" do %><i class="far fa-plus-square"></i><% end %>
  </li>

  <li class="nav-item">
    <%= link_to ranks_path, class: "nav-link deco text-dark" do %><i class="fas fa-award"></i><% end %>
  </li>

  <li class="nav-item">
    <%= link_to rooms_path, class: "nav-link deco text-dark" do %>
      <i class="fas fa-envelope icon_layers_icon"></i>
    <% end %>
  </li>

  <li class="nav-item">
    <%= link_to notifications_path, class: "nav-link deco" do %>
      <% if unchecked_notifications.any? %>
      <span class="icon_layers fa-fw text-dark">
        <i class="fas fa-bell icon_layers_icon"></i>
        <% if unchecked_notifications.exists? %>
          <span class="icon_layers_counter rounded-circle text-center"><%= unchecked_notifications.count %></span>
        <% end %>
      </span>
      <% else %>
      <i class="fas fa-bell text-dark"></i>
      <% end %>
    <% end %>
  </li>

  <li class="nav-item">
    <%= link_to my_page_user_path(current_user.id), class: "nav-link deco text-dark" do %><i class="fas fa-user-circle"></i><% end %>
  </li>

  <li class="nav-item">
    <%= link_to destroy_user_session_path, method: :delete, class: "nav-link deco text-dark" do %><i class="fas fa-sign-out-alt"></i><% end %>
  </li>
<% else %>

  <li class="nav-item">
    <%= link_to logs_path,  class: "nav-link deco text-dark" do %><i class="far fa-list-alt"></i><% end %>
  </li>

  <li class="nav-item">
    <%= link_to ranks_path, class: "nav-link deco text-dark" do %><i class="fas fa-award"></i><% end %>
  </li>

  <li class="nav-item">
    <%= link_to new_user_registration_path, class: "nav-link deco text-dark" do %><i class="fas fa-plus"></i><% end %>
  </li>

  <li class="nav-item">
    <%= link_to new_user_session_path, class: "nav-link deco text-dark" do %><i class="fas fa-sign-in-alt"></i><% end %>
  </li>
<% end %>

app/views/layouts/_humburger.html.erb
<% if user_signed_in? %>
  <li>
    <%= link_to logs_path do %>Log List<% end %>
    <p>投稿一覧</p>
  </li>

  <li>
    <%= link_to new_log_path do %>New Log<% end %>
    <p>新規投稿</p>
  </li>

  <li>
    <%= link_to ranks_path do %>Ranking<% end %>
    <p>ランキング</p>
  </li>

  <li>
    <%= link_to rooms_path do %>DM List<% end %>
    <p>ダイレクトメッセージ</p>
  </li>

  <li>
    <%= link_to my_page_user_path(current_user.id) do %>My Page<% end %>
    <p>マイページ</p>
  </li>

  <li>
    <%= link_to destroy_user_session_path, method: :delete do %>Log Out<% end %>
    <p>ログアウト</p>
  </li>
<% else %>
  <li>
    <%= link_to logs_path do %>Log List<% end %>
    <p>投稿一覧</p>
  </li>

  <li>
    <%= link_to ranks_path do %>Ranking<% end %>
    <p>ランキング</p>
  </li>

  <li>
    <%= link_to new_user_registration_path do %>Sign Up<% end %>
    <p>会員登録</p>
  </li>

  <li>
    <%= link_to new_user_session_path do %>Sign In<% end %>
    <p>ログイン</p>
  </li>

  <li>
    <%= link_to users_guest_sign_in_path, method: :post do %>Guest<% end %>
    <p>ゲストログイン</p>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portforio1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= include_gon %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Sawarabi+Gothic" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Caveat" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Sawarabi+Mincho" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <nav class="navbar navbar-expand-sm">
        <div class="container">
          <%= link_to root_path, class: "navbar-bland deco navbar-brand-center" do %><h1 class="nav-logo">DivIn</h1><% end %>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
             <ul class="navbar-nav">
              <%= render "layouts/header" %>
            </ul>
          </div>

          <div id="sp-menu">
            <ul>
              <%= render "layouts/humburger" %>
            </ul>
          </div>

          <div id="hm-icon">
            <span class="menu-trigger">
              <span></span>
              <span></span>
              <span></span>
            </span>
          </div>

        </div>
      </nav>
    </header>

    <%= yield %>
  </body>
</html>